### ISSUE TITLE
button for summary of timereport

### ISSUE THREAD

**Issue by kamigerami** [codelabsab/timereport-ui#26]
An idea is to have a button on the website (UI) to download a report for a given month in some format so it can be sent to for example our economy department for when they do the payroll each month.

Today I have to go in -> copy paste it in to a E-mail and send it.

Any other suggestions are welcomed.

**Comment by mattiaslundberg** [comment]
Downloading will be tricky without adding the formatting and output to `timereport-api`, other (easier) options are:

1. Add a button that copies to the clipboard that you can paste to an email
2. Add a button and view (render everything to html) that outputs a page with the overall summary
3. Send an email after someone locks directly to you (to verify and forward to economy), this will only contain information for the person that locked
4. Send an email after everyone has locked (might cause issues if someone leaves the company since we don't have a good way to handle who is expected to lock)

What do you think?

Regarding format is something simple like this good enough:

```
Mattias
2020-09-01 sjuk 8h

Kami
2020-09-03 sjuk 8h
```

**Comment by kamigerami** [comment]
Great ideas! 

1. clip board is great
2. yes maybe this page can be "public" without having to log in so it can be shared to third party.

no need to do E-mail sending stuff - we will require to have a E-mail service etc .
